name: Deploy Auth Service

on:
  push:
    branches: 
      - main
      - feature/AA-043-service-deployemt-confige
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'
        
    - name: Install dependencies
      working-directory: ./auth-service
      run: |
        echo "Installing dependencies..."
        npm install --production
        echo "Dependencies installed successfully"
      
    - name: Prepare for deployment
      run: |
        echo "Creating deployment package..."
        cd auth-service
        # Remove local Firebase service account if exists
        rm -f firebase-service-account.json
        zip -r ../release.zip ./*
        echo "Deployment package created successfully"
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'autoalert-auth-service'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_AUTH_SERVICE }}
        package: release.zip 