name: Deploy Tutorial Service

on:
  push:
    branches: 
      - main
      - feature/AA-049-tutorial-service-deployment
    paths:
      - 'tutorial-service/**'
      - '.github/workflows/tutorial-service-deploy.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: autoalert-tutorial-service
  AZURE_WEBAPP_PACKAGE_PATH: tutorial-service
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      working-directory: ./tutorial-service
      run: |
        echo "Installing dependencies..."
        npm install --production
        echo "Dependencies installed successfully"
      
    - name: Prepare for deployment
      run: |
        echo "Creating deployment package..."
        cd tutorial-service
        zip -r ../release.zip ./*
        echo "Deployment package created successfully"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.TUTORIAL_SERVICE_PUBLISH_PROFILE }}
        package: release.zip 