name: Deploy User Service

on:
  push:
    branches: 
      - main
      - feature/AA-043-service-deployemt-confige
    paths:
      - 'user-service/**'
      - '.github/workflows/user-service-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'
        
    - name: Install dependencies
      working-directory: ./user-service
      run: |
        npm ci
        npm run build
      
    - name: Zip artifact for deployment
      run: zip -r release.zip ./user-service/*
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'autoalert-user-service'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_USER_SERVICE }}
        package: release.zip 