name: Deploy User Service

on:
  push:
    branches: 
      - main
      - feature/AA-043-service-deployemt-confige
    paths:
      - 'user-service/**'
      - '.github/workflows/user-service-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      working-directory: ./user-service
      run: npm ci
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'autoalert-user-service'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_USER_SERVICE }}
        package: ./user-service 